### ISSUE TITLE
HMR broken

### ISSUE THREAD

**Issue by masylum** [vanilla-extract-css/vanilla-extract#1621]
### Describe the bug

I think yesterday's release of 5.1.0 broke HMR.
If I use unstable_mode: 'inlineCssInDev' it works, though.

### Reproduction

Just update to 5.1.0 and HMR stops working

### System Info

```shell
System:
    OS: macOS 15.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 77.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.11.0 - /opt/homebrew/bin/node
    npm: 10.9.2 - /opt/homebrew/bin/npm
    pnpm: 10.2.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 137.0.7151.122
    Safari: 18.3
  npmPackages:
    @vanilla-extract/css: ^1.17.4 => 1.17.4
    @vanilla-extract/css-utils: ^0.1.6 => 0.1.6
    @vanilla-extract/recipes: ^0.5.7 => 0.5.7
    @vanilla-extract/vite-plugin: ^5.1.0 => 5.1.0
```

### Used Package Manager

pnpm

### Logs

```shell

```

### Validations

- [x] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@masylum The 5.1.0 release should not have affected any existing code. Only setting `unstable_mode: 'inlineCssInDev'` should change behaviour during dev. Without a minimal reproduction I'm unable to invest any more time in your issue.

**Comment by askoufis** [comment]
@masylum After a quick test in both the repo's fixture and a Vite test app, HMR seems to be working fine.

**Comment by masylum** [comment]
hmm.. I will try to create a repro case then and reopen it.

**Comment by masylum** [comment]
Ok, so I have a way to reproduce it. I've just installed a default astro site, added the vite plugin. And I can confirm that reload does not work. I have no idea whether this is Astro's, or Vite's or Vanilla Extract's culprit.

pnpm create astro@latest
pnpm add -D @vanilla-extract/vite-plugin

```diff
// astro.config.mjs
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
+ import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
	site: 'https://example.com',
	integrations: [mdx(), sitemap()],
+	vite: {
+		plugins: [vanillaExtractPlugin()],
+	},
});
```

Then just add any vanilla extract class to any element:

```diff
+// index.css.ts
+import { style } from "@vanilla-extract/css"
+
+export const fooClass = style({
+  color: 'green',
+})
```

```diff
---
import BaseHead from "../components/BaseHead.astro";
import Header from "../components/Header.astro";
import Footer from "../components/Footer.astro";
import { SITE_TITLE, SITE_DESCRIPTION } from "../consts";
+import { fooClass } from "./index.css";
---

<!doctype html>
<html lang="en">
	<head>
		<BaseHead title={SITE_TITLE} description={SITE_DESCRIPTION} />
	</head>
	<body>
		<Header />
		<main>
-			<h1>🧑‍🚀 Hello, Astronaut!</h1>
+			<h1 class={fooClass}>🧑‍🚀 Hello, Astronaut!</h1>
...
```

And now try to change the color of the class, and it won't work. Restarting astro will.

**Comment by hotyes** [comment]
same here, @masylum  did you find a solution? thanks

**Comment by masylum** [comment]
no, I'm restarting astro on each CSS change...

**Comment by sebastianromero** [comment]
Same issue here. I had to roll back to version 5.0.0.

**Comment by 00x4** [comment]
Using with Astro.

5.0.6 -> Works
5.0.7 -> Doesn't work

This appears to be caused by #1617, but I'm not sure if it's a problem with vite-plugin or something else.

**Comment by askoufis** [comment]
Please try out this snapshot version: `@vanilla-extract/vite-plugin@5.1.2-vite-hmr-fix-20250826075423`. In my testing it seems to have fixed the HMR issue in Astro, as well as generally improved HMR by reducing unnecessary invalidations.

**Comment by masylum** [comment]
it works!! awesome! ❤️

**Comment by jojojojojoj5564656465465** [comment]
Hello, 

I am using Qwik City , HMR is also broken but fixed with 5.0.6 hope it will be soon fixed.

**Comment by FraserThompson** [comment]
Can confirm @askoufis snapshot above fixes the issue experienced when using this plugin with astro and makes development much less frustrating.

**Comment by zhaohuanyuu** [comment]
> no, I'm restarting astro on each CSS change...

This issue still exists in version 5.1.3. When will this fix be merged into the official version? @askoufis

**Comment by adam-marostica-nl** [comment]
The hmr-fix had resolved my HMR issue for a few weeks, but as of last week, it no longer works. Has there been any progress on resolving the HMR issue in an official version?

**Comment by prests** [comment]
@askoufis is there something different between build `5.1.2-vite-hmr-fix-20250826075423` and build `5.1.4` in terms of HMR? Has this fix been merged yet?

I was running into issues with HMR on astro when using vanilla-extract's vite plugin v5.1.4 and this canary build seems to fix that issue. Was wondering if this will be stable anytime soon.

Thanks!

**Comment by PBarriaUrenda** [comment]
I am also experimenting this issue. Going back to `5.1.2-vite-hmr-fix-20250826075423` did not fix it, for what is worth.

**Comment by askoufis** [comment]
This should be fixed by in the latest version of the vite plugin. https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fvite-plugin%405.2.1

**Comment by prests** [comment]
@askoufis I just noticed in my astro project by moving from `v5.1.2-vite-hmr-fix-20250826075423` to `v5.2.1` I am seeing a regression in how the vite plugin orders it's stylesheets.

v5.2.1:
<img width="866" height="302" alt="Image" src="https://github.com/user-attachments/assets/b2cfa41d-af63-4427-95bc-d250400d1065" />

v5.1.2-vite-hmr-fix-20250826075423
<img width="1716" height="535" alt="Image" src="https://github.com/user-attachments/assets/7149b352-04e0-470b-ba9e-b25caa247c64" />

I can try and find some time later to create a proper reproduction, but just wanted to call it out!

EDIT: This may actually be a vite/astro issue: https://github.com/withastro/astro/issues/10065
